import {TokenCreator} from "../Match/Shop/TokenCreator";

let token = TokenCreator()
export const PATH = {
    HOME: '/',
    CARDS: '/cards',
    WORD: '/word',
    SEARCH: '/search',
    TEST: '/secret',
    GAME: '/game',
    MATCH: '/match',
    FILTRON: '/filtron',
    ONE: '/classicOnee',
    TWO: '/classicTtwo',
    THREE: '/classicsthree',
    FOUR: '/classicfourrr',
    FIVE: '/classicGfive',
    HALFONE: '/halfOne',
    HALFTWO: '/halfTwoTwo',
    HALFTHREE: '/halfThreee',
    HALFFOUR: '/halffourPart',
    CLASSICWITHROTATEONE: '/claRotOne',
    CLASSICWITHROTATETWO: '/clRoTw',
    CLASSICWITHROTATETHREE: '/cloassRotaTg',
    CLASSICWITHROTATEFOUR: '/crf',
    TRIPLEMATCHONE: '/tripleMatchOne',
    THREEMATCHESTWO: '/threeMatchesTwo',
    THREEMATCHESTWOROTATEONE: '/threeMatchesTwoRotateOne',
    THREEMATCHESTWOROTATETWO: '/threeMatchesTwoRotateTwo',
    POLMOONE: '/polmoOne',
    POLMOTWO: '/polmoTwo',
    POLMOTHREE: '/polmoThree',
    POLMOFOUR: '/plmfr',
    CLASSICPATTERNONE: '/clpatternOne',
    CLASSICPATTERNTWO: '/asspatternTwo',
    CLASSICPATTERNTHREE: '/icpatternTh',
    CLASSICPATTERNFOUR: '/clppatternfo',
    REFLIPONE: '/reflipOne',
    REFLIPTWO: '/reflipTwo',
    REFLIPTHREE: '/refliptr',
    REFLIPFOUR: '/refFo',

    CARSBYMODELSONE: '/carsByModelsOne',
    CARSBYMODELSTWO: '/carsModelsTwo',
    CARSBYMODELSTHREE: '/ByModelsThree',
    CARSBYMODELSFOUR: '/autocarsModelsFour',
    PATRICKFIRST: '/patrickFirst',
    PATRICKSECOND: '/patrickSecond',
    PATRICKTHIRD: '/patrickThird',
    PATRICKFOUR: '/patrickFFor',
    ROTATEPATTERNONE: '/rotatePatternOne',
    ROTATEPATTERNTWO: '/rotatePatternTwo',
    PATRICKROTATEONE: '/patrickRotate',
    PATRICKROTATETWO: '/patrickRotateTwo',
    TESTPATTERN: '/testPatt',
    CRAZYONE: '/crazyOne',
    //PATRPATTROT: '/ppr',
    CIRCLE: '/circle',
    ROTATECIRCLE: '/rotateCircle',
    MODAL: '/modal',
    TRIPLETSET: '/tripletest',
    PROFILE: '/profile',
    PACKOPENER: `/packOpener+${token}`,
    SHOP: '/shop',
    SETTINGS: '/gameSettings',
    BATIS: '/batis'
};

